export const profile = {
  name: '윤정민',
  nameEn: 'Yoon Jeongmin',
  role: 'Robot Software Engineer',
  email: 'jmyoon110@gmail.com',
  github: 'https://github.com/yjmini',
  location: 'Gwangju, Korea',
  focus: 'ROS2 · Reinforcement Learning · Simulation · Vision',
}

export const projects = [
  {
    slug: 'hydraulic-robot-rl',
    index: '01',
    year: '2025',
    title: '유압식 고하중 로봇 PPO 제어',
    shortTitle: 'Hydraulic Robot RL',
    tagline: 'Isaac Lab 정책 학습에서 실제 ROS2 적용 제약까지',
    summary: 'Isaac Lab에서 유압식 고하중 로봇의 전진 정책을 학습하고, reward cheating과 자세 불안정을 로그·영상으로 분석했습니다. 정책 export 이후 실제 로봇의 명령 범위, 제어 주기, 유압 응답 지연과 안전 조건까지 연결해 적용 가능성을 검토했습니다.',
    image: 'assets/projects/hydraulic-robot.jpg',
    imagePosition: 'center 18%',
    status: 'KAERI 개인 과제',
    featured: true,
    private: true,
    stack: ['Isaac Lab', 'Isaac Sim', 'RSL-RL', 'PPO', 'PyTorch', 'ROS2'],
    metrics: [{ value: 'PPO', label: 'policy learning' }, { value: 'Sim→Real', label: 'deployment review' }],
    role: '학습 환경·보상 설계·로그 분석·Deploy 검토',
    period: '2025.08 — 2025.12',
    problem: '학습된 로봇이 앞으로 이동하지 않고 제자리에서 몸만 흔들며 전진 보상을 얻는 reward cheating이 발생했습니다.',
    decision: '하나의 총 reward만 보지 않고 전진 속도, 자세 안정성, 관절 움직임 penalty를 분리해 W&B/TensorBoard 로그와 실패 영상을 함께 비교했습니다.',
    result: '보상 항목 간 우선순위를 재조정하고, 시뮬레이션 성능만으로 끝내지 않고 실제 로봇의 command limit·추론 지연·제어 주기를 후속 검증 항목으로 정리했습니다.',
    highlights: ['Observation/action space와 reward 항목을 명시적으로 분리', '학습 로그와 실패 영상을 같은 타임라인으로 비교', '실제 유압 응답과 안전 한계를 Deploy 체크리스트에 반영'],
  },
  {
    slug: 'smart-assembly-transport',
    index: '02',
    year: '2026',
    title: '스마트 조립·무인 운송 시스템',
    shortTitle: 'Smart Assembly & Transport',
    tagline: '음성 작업 지시부터 조립·검사·배송까지 연결한 ROS2 시스템',
    summary: 'STT 작업 지시, ROS2 FSM, 컨베이어, YOLO/OpenCV 검사, Dobot 조립, TurtleBot/Nav2 배송, Django API와 Vue 관제 화면을 하나의 실행 흐름으로 통합했습니다. 실제 장비 없이도 검증할 수 있도록 Mock 우선 구조와 단계별 테스트를 함께 설계했습니다.',
    image: 'assets/projects/smart-assembly.svg',
    imagePosition: 'center',
    status: 'Actively maintained',
    featured: true,
    stack: ['ROS2', 'Python', 'Django', 'Vue', 'YOLO', 'Nav2', 'WebSocket'],
    metrics: [{ value: 'E2E', label: 'integrated flow' }, { value: 'Mock-first', label: 'hardware-safe test' }],
    role: '시스템 아키텍처·FSM·로봇/웹 통합·검증',
    period: '2026.05 — 현재',
    problem: '여러 로봇과 웹 서비스가 순차적으로 협업해야 하지만, 장비 가용성과 네트워크 상태에 따라 전체 흐름 검증이 쉽게 막혔습니다.',
    decision: '각 장비를 동일 인터페이스의 Mock으로 먼저 대체하고, ROS2 FSM이 실제/Mock 구현을 바꾸어 끼울 수 있게 경계를 분리했습니다.',
    result: '음성 명령에서 조립·검사·배송·관제까지 전체 상태 전이를 반복 실행할 수 있는 검증 가능한 통합 구조를 만들었습니다.',
    highlights: ['ROS2 FSM 중심의 단계별 오케스트레이션', 'Django API·WebSocket·Vue 대시보드 연동', '카메라·컨베이어·Dobot·TurtleBot Mock 지원'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/smart-assembly-transport' }],
  },
  {
    slug: 'go1-remote-inspection',
    index: '03',
    year: '2025',
    title: 'Unitree Go1 원격 점검 시스템',
    shortTitle: 'Go1 Remote Inspection',
    tagline: 'RGB-D SLAM·객체 인식·원격 ROS 통신을 하나의 현장 흐름으로',
    summary: 'Jetson Orin NX와 RealSense, RTAB-Map, YOLOv10, OpenVPN을 연결해 접근 제한 환경의 원격 점검 로봇을 구현했습니다. 온보드와 GCS의 연산을 나누고 RViz에서 3D 지도와 탐지 결과를 확인할 수 있게 구성했습니다.',
    image: 'assets/projects/go1-remote.png',
    imagePosition: 'center',
    status: '2× 우수상',
    featured: true,
    stack: ['Unitree Go1', 'Jetson Orin NX', 'RealSense', 'ROS1', 'RTAB-Map', 'YOLOv10'],
    metrics: [{ value: '2×', label: 'awards' }, { value: 'RGB-D', label: 'mapping + vision' }],
    role: 'VPN/ROS 통신·SLAM·객체 인식·연산 분산',
    period: '2025.01 — 2025.05',
    problem: 'LTE/OpenVPN 환경에서 SLAM, 객체 인식, 원격 시각화를 동시에 실행하면 지연과 연결 장애의 원인을 찾기 어려웠습니다.',
    decision: 'ping → VPN tunnel → ROS topic list/echo → RViz 순서의 계층별 점검 루틴을 만들고, Jetson과 GCS 사이의 연산 역할을 분리했습니다.',
    result: '졸업연구작품 우수상과 AI Festa 경진대회 우수상을 수상했으며, 네트워크부터 인식·시각화까지 통합 디버깅 절차를 확보했습니다.',
    highlights: ['OpenVPN 기반 원격 ROS 네트워크', 'RTAB-Map 3D 지도와 YOLO 탐지 결과 통합', 'Jetson/GCS 연산 분산과 장애 계층화'],
  },
  {
    slug: 'hazardous-process-automation',
    index: '04',
    year: '2025',
    title: '고위험 작업 로봇 공정 자동화',
    shortTitle: 'Process Automation',
    tagline: '제어 코드만이 아니라 작업물 정렬과 전용 가이드까지 함께 설계',
    summary: '반복적이고 위험한 수작업을 로봇 공정으로 전환하기 위해 작업을 동작 단위로 분해하고, MoveIt 경로·작업물 기준 위치·전용 가이드 구조를 함께 검토했습니다.',
    image: 'assets/projects/process-automation.png',
    imagePosition: 'center',
    status: 'KAERI 개인 과제',
    featured: true,
    stack: ['ROS2', 'MoveIt', 'Python', 'SolidWorks', 'Process Design'],
    metrics: [{ value: 'SW+HW', label: 'co-design' }, { value: 'Follow-up', label: 'research planning' }],
    role: '공정 분해·경로 검토·가이드 모델 설계',
    period: '2025.07 — 2025.10',
    problem: '시뮬레이션에서 계획한 경로와 실제 작업 위치가 일치하지 않아 같은 명령의 반복성이 떨어졌습니다.',
    decision: '경로 코드만 수정하지 않고 end-effector 접근 방향, 작업물 고정 기준, 가이드 구조 오차를 함께 보정했습니다.',
    result: '반복 가능한 자동화 조건을 SW·기구 관점에서 함께 정리했고, 공정 분석 결과가 후속 연구 과제 기획으로 연결됐습니다.',
    highlights: ['수작업 공정을 로봇 동작 단위로 분해', 'MoveIt 경로와 실제 기준 위치 비교', 'SolidWorks 전용 가이드 구조 보정'],
  },
  {
    slug: 'ros2-control-ui',
    index: '05',
    year: '2025',
    title: 'ROS2 고하중 로봇 제어 UI',
    shortTitle: 'ROS2 Control UI',
    tagline: '상태 구독과 명령 발행을 분리한 안전 중심 제어 화면',
    summary: 'PyQt5/Qt Designer로 고하중 로봇의 상태 모니터링과 명령 발행 흐름을 분석하고, hold·preset·master mode 조건에 따라 버튼이 활성화되도록 제어 로직을 정리했습니다.',
    image: 'assets/projects/robot-ui.png',
    imagePosition: 'center',
    status: 'KAERI 개인 과제',
    stack: ['ROS2 Humble', 'rclpy', 'Python', 'PyQt5', 'Qt Designer'],
    metrics: [{ value: 'State-led', label: 'safe control' }, { value: 'ROS2', label: 'pub/sub UI' }],
    role: 'UI 구조 분석·topic 연동·상태 기반 버튼 로직',
    period: '2025.07',
    problem: 'GUI 이벤트와 ROS2 callback 타이밍이 다르면 화면 상태와 실제 로봇 상태가 어긋날 가능성이 있었습니다.',
    decision: 'robot_to_ui 상태 수신과 ui_action 명령 발행을 분리하고, 실제 상태를 기준으로 버튼 활성 조건을 정의했습니다.',
    result: 'UI를 단순 조작 화면이 아니라 안전한 명령 전달을 위한 ROS2 제어 소프트웨어 구성 요소로 개선했습니다.',
    highlights: ['Qt 이벤트 루프와 ROS2 callback 구조 조정', '상태 기반 버튼 활성화', '명령 전후 로봇 상태 재확인 흐름'],
  },
  {
    slug: 'yolov10-ros',
    index: '06',
    year: '2025',
    title: 'YOLOv10 ROS Integration',
    shortTitle: 'YOLOv10 ROS',
    tagline: '카메라 입력을 탐지 결과와 시각화 topic으로 변환하는 ROS 패키지',
    summary: 'ROS Noetic 카메라 이미지를 구독해 YOLOv10 추론을 실행하고, bounding box와 시각화 이미지를 다시 topic으로 발행하는 로봇 인식 패키지입니다.',
    image: 'assets/projects/go1-demo.jpg',
    imagePosition: 'center',
    status: 'Public repository',
    stack: ['ROS Noetic', 'Python', 'YOLOv10', 'OpenCV'],
    role: 'ROS 이미지 파이프라인·추론·결과 message 발행',
    period: '2025',
    problem: '로봇 카메라 프레임과 딥러닝 추론 결과를 기존 ROS 노드들이 재사용할 수 있는 형태로 전달해야 했습니다.',
    decision: '입력 이미지, bounding box, annotation 이미지를 독립 topic으로 나눠 소비 노드가 필요한 정보만 선택하도록 구성했습니다.',
    result: '원격 점검 로봇의 객체 인식 기능을 재사용 가능한 ROS 패키지 단위로 정리했습니다.',
    highlights: ['sensor_msgs/Image 입력 처리', 'Bounding box와 시각화 출력 분리', 'YOLO 추론을 ROS graph에 통합'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/yolov10_ros' }],
  },
  {
    slug: 'yolo-head-tracking',
    index: '07',
    year: '2026',
    title: 'YOLO Head Tracking',
    shortTitle: 'Head Tracking',
    tagline: '탐지·ByteTrack ID·포즈 키포인트로 이동과 시선 방향 추정',
    summary: '사용자 정의 YOLO 머리 탐지 모델과 ByteTrack, 포즈 키포인트 모델을 결합해 사람별 이동 방향과 얼굴 방향을 추정하고 결과를 대시보드로 시각화했습니다.',
    image: 'assets/projects/isaac-sim.jpg',
    imagePosition: 'center',
    status: 'Public repository',
    stack: ['YOLO', 'ByteTrack', 'Pose', 'Python', 'Jupyter'],
    role: '탐지·추적·방향 추정 파이프라인',
    period: '2026',
    problem: '단일 프레임의 머리 탐지만으로는 같은 사람의 이동 흐름과 얼굴 방향을 안정적으로 설명하기 어려웠습니다.',
    decision: '탐지 결과에 track ID를 붙이고 포즈 키포인트 기반 얼굴 방향을 별도 모델에서 계산하는 이중 파이프라인을 사용했습니다.',
    result: '사람별 이동 방향과 시선 방향을 함께 확인할 수 있는 데모 파이프라인을 구성했습니다.',
    highlights: ['Custom YOLO head detector', 'ByteTrack 기반 ID 유지', 'Pose keypoint 기반 얼굴 방향'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/YOLO_head_tracking' }],
  },
  {
    slug: 'robot-study',
    index: '08',
    year: '2026',
    title: 'Robot Study Lab',
    shortTitle: 'Robot Study',
    tagline: '센서 좌표부터 Manipulation·SLAM·WebSocket까지 재현 가능한 실습 기록',
    summary: 'RealSense RGB-D 좌표, YOLO, Dobot pick-and-place, SLAM, URDF/Xacro, TF, RViz, Gazebo, RoboDK와 WebSocket 연동을 작은 단위로 구현하고 기록한 로봇 기술 실험 저장소입니다.',
    image: 'assets/projects/ui-demo.jpg',
    imagePosition: 'center',
    status: 'Learning archive',
    stack: ['ROS2', 'RealSense', 'Dobot', 'SLAM', 'Gazebo', 'RoboDK'],
    role: '기술별 최소 재현 예제·통합 실험',
    period: '2026 — 현재',
    problem: '로봇 프로젝트의 문제는 하나의 프레임워크가 아니라 좌표계·센서·통신·제어 경계에서 자주 발생했습니다.',
    decision: '기술별 최소 예제를 먼저 만들고 입력·출력·실패 조건을 기록한 뒤 통합 프로젝트에 재사용했습니다.',
    result: '새 로봇/센서 조합을 검증할 때 재사용할 수 있는 실습 아카이브를 축적했습니다.',
    highlights: ['RGB-D 픽셀→3D 좌표', 'Dobot pick-and-place', 'URDF/TF/RViz/Gazebo 실험'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/robot_study' }],
  },
  {
    slug: 'websocket-live-streaming',
    index: '09',
    year: '2026',
    title: 'WebSocket Live Streaming',
    shortTitle: 'Live Streaming',
    tagline: '브라우저 화면 공유와 실시간 채팅을 WebSocket으로 중계',
    summary: 'getDisplayMedia와 canvas frame capture를 이용해 브라우저 화면을 공유하고, Node.js/Vue WebSocket 서버를 통해 채팅과 화면 프레임을 실시간 중계했습니다.',
    image: null,
    status: 'Public repository',
    stack: ['Vue', 'Node.js', 'WebSocket', 'Canvas API'],
    role: '실시간 이벤트·프레임 중계·클라이언트 UI',
    period: '2026',
    problem: '브라우저에서 캡처한 화면과 채팅 이벤트를 같은 실시간 연결에서 안정적으로 구분해 전달해야 했습니다.',
    decision: '이벤트 타입과 payload를 분리하고, 화면은 canvas 프레임으로 변환해 WebSocket으로 중계했습니다.',
    result: '별도 네이티브 앱 없이 브라우저 간 화면 공유와 채팅이 동작하는 프로토타입을 완성했습니다.',
    highlights: ['getDisplayMedia 화면 캡처', 'Canvas frame relay', 'Vue 실시간 UI'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/websocket_live_streaming' }],
  },
  {
    slug: 'langchain-todo',
    index: '10',
    year: '2026',
    title: 'Natural-language Todo',
    shortTitle: 'LangChain Todo',
    tagline: '자연어를 로컬 LLM이 구조화된 일정 작업으로 변환',
    summary: 'LangChain과 Ollama/Qwen3, Express를 연결해 자연어로 입력한 할 일을 구조화하고 REST API 기반 목록에 반영하는 로컬 AI 인터페이스를 만들었습니다.',
    image: null,
    status: 'Prototype',
    stack: ['LangChain', 'Ollama', 'Qwen3', 'Express', 'JavaScript'],
    role: '자연어 처리 chain·API·웹 UI',
    period: '2026',
    problem: '자유 형식 자연어를 일정 앱이 처리할 수 있는 안정적인 구조로 바꾸는 경계가 필요했습니다.',
    decision: 'LLM 출력 형식을 제한하고 변환 결과를 Express REST API의 명시적 작업으로 매핑했습니다.',
    result: '로컬 모델만으로 자연어 일정 등록 흐름을 검증한 프로토타입을 만들었습니다.',
    highlights: ['Local LLM workflow', 'Structured action mapping', 'REST 기반 상태 관리'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/Langchain_based_todolist' }],
  },
  {
    slug: 'langgraph-cuso',
    index: '11',
    year: '2026',
    title: 'CuSo Cooking Supporter',
    shortTitle: 'CuSo',
    tagline: '조리 과정을 상태 그래프로 다루는 LangGraph 프로토타입',
    summary: '조리 지원 흐름을 단계와 상태 전이로 표현하기 위해 LangGraph 기반 client/server 구조를 실험한 초기 프로토타입입니다.',
    image: null,
    status: 'Early prototype',
    stack: ['LangGraph', 'Python', 'Client/Server'],
    role: '상태 그래프·프로토타입 구조',
    period: '2026',
    problem: '조리 안내는 단일 질의응답보다 현재 단계와 예외를 기억하는 상태 기반 흐름이 필요했습니다.',
    decision: '질문을 한 번에 처리하지 않고 단계별 node와 transition으로 나눠 실험했습니다.',
    result: '그래프 기반 AI 워크플로의 최소 client/server 구조를 확인했습니다.',
    highlights: ['State graph prototype', '단계별 node/transition', 'Client/server separation'],
    links: [{ label: 'GitHub', href: 'https://github.com/yjmini/LangGraph-CookingSupporter-CuSo' }],
  },
  {
    slug: 'early-software-projects',
    index: '12',
    year: '2022—24',
    title: '초기 소프트웨어 프로젝트',
    shortTitle: 'Software Foundations',
    tagline: 'Unity 3D 콘텐츠와 모듈형 C 게임으로 쌓은 구현 기반',
    summary: 'Unity 3D 캐주얼 게임 CatsGo와 4인용 콘솔 카드 게임 The Great Dalmuti를 구현하며 상태 관리, 입력 처리, 모듈 분리와 인터랙션 설계의 기본기를 쌓았습니다.',
    image: null,
    status: 'Archive',
    stack: ['Unity', 'C#', 'C', 'Game Logic'],
    role: '게임 로직·인터랙션·모듈 구현',
    period: '2022 — 2024',
    problem: '복잡한 규칙과 사용자 입력을 한 파일에 쌓지 않고 변경 가능한 구조로 관리해야 했습니다.',
    decision: '라운드·등급·카드 제출·공물 규칙을 기능별로 분리하고 상태 전이를 명시적으로 구현했습니다.',
    result: '이후 로봇 FSM과 실시간 UI를 설계할 때 이어지는 상태 중심 구현 기반을 만들었습니다.',
    highlights: ['Unity 3D interaction', 'C 모듈 분리', '상태/규칙 기반 로직'],
    links: [
      { label: 'CatsGo', href: 'https://github.com/yjmini/MTVS2022_CatsGo' },
      { label: 'Dalmuti', href: 'https://github.com/yjmini/The-Great-Dalmuti' },
    ],
  },
]

export const experience = [
  {
    period: '2026.01 — 현재',
    place: 'Samsung Software AI Academy for Youth',
    role: 'SSAFY 15기 · Embedded Robotics Track',
    location: 'Gwangju · Full-time training',
    current: true,
    summary: 'C/C++, Python, Linux, ROS2와 센서·비전·제어를 실제 장비 및 Mock 환경에서 연결하고 있습니다.',
    bullets: ['스마트 조립·무인 운송 통합 프로젝트', 'ROS2·Dobot·TurtleBot·Raspberry Pi 실습', '삼성 SW 역량 테스트 A형 취득 · 내부 평가 평균 약 90점'],
  },
  {
    period: '2025.06 — 2025.12',
    place: 'Korea Atomic Energy Research Institute',
    role: 'KAERI 로봇응용연구실 · 인턴연구원',
    location: 'Daejeon · On-site',
    summary: '강화학습 제어, 고위험 작업 자동화, ROS2 제어 UI를 각각 학습·공정·운영 관점에서 수행했습니다.',
    bullets: ['Isaac Lab/PPO 기반 유압식 고하중 로봇 제어 가능성 검토', 'MoveIt·SolidWorks 기반 로봇 공정과 전용 가이드 공동 설계', 'PyQt5·ROS2 topic 기반 상태 중심 제어 UI 개선'],
  },
  {
    period: '2025.01 — 2025.09',
    place: 'KOREATECH Graduation Project',
    role: 'Unitree Go1 원격 점검 로봇 · 팀 프로젝트',
    location: 'Cheonan · Team project',
    summary: '접근 제한 환경에서 3D 지도와 객체 정보를 원격 조작자에게 전달하는 로봇 시스템을 개발했습니다.',
    bullets: ['Jetson·RealSense·RTAB-Map·YOLO 통합', 'OpenVPN 기반 원격 ROS 통신', '졸업연구작품 우수상 · AI Festa 경진대회 우수상'],
  },
  {
    period: '2022.03 — 2022.06',
    place: 'Chungcheong AI Expert Mentoring',
    role: 'AI 프로젝트 참여자',
    location: 'Team project',
    summary: 'AI 문제 정의와 프로토타입 검증 과정을 팀으로 수행했습니다.',
    bullets: ['대전정보문화산업진흥원 최우수상', '데이터·모델·데모 흐름을 팀 산출물로 정리'],
  },
]

export const toolGroups = [
  { name: 'Robot software', tools: ['ROS2 Humble', 'ROS1 Noetic', 'rclpy', 'MoveIt', 'Nav2', 'TF', 'RViz'] },
  { name: 'Simulation & RL', tools: ['Isaac Sim', 'Isaac Lab', 'RSL-RL', 'PPO', 'Gazebo', 'MuJoCo', 'RoboDK'] },
  { name: 'Vision & AI', tools: ['PyTorch', 'YOLO', 'OpenCV', 'RealSense RGB-D', 'RTAB-Map', 'VQA'] },
  { name: 'Systems & delivery', tools: ['C++', 'Python', 'Linux', 'Docker', 'Jetson', 'Raspberry Pi', 'Django', 'Vue'] },
]

export const awards = [
  ['AI Festa 경진대회 우수상', 'KOREATECH · 2025'],
  ['졸업연구작품 우수상', 'KOREATECH · 2025'],
  ['충청권 AI 전문가 멘토링 최우수상', 'DICIA · 2022'],
]

export const certifications = [
  ['정보처리기사', '2026'],
  ['Samsung SW Competency A', '2026'],
  ['SQLD', '2023'],
  ['ADsP', '2023'],
]
