export const copyrightPolicy = {
  owner: 'Yoon Jeongmin',
  ownerKo: '윤정민',
  email: 'jmyoon110@gmail.com',
  effectiveDate: '2026-08-18',
  effectiveLabel: '2026. 08. 18.',
  notice: '© 2026 Yoon Jeongmin. All rights reserved except where a separate license applies.',
  introduction: '이 페이지는 포트폴리오에 포함된 글, 편집 구성, 그래픽, 사진, 영상과 프로젝트 자료의 권리 범위 및 이용 조건을 안내합니다.',
  permissions: [
    '비영리 목적의 개인 학습과 참고를 위한 웹페이지 열람',
    '내용을 복제하지 않고 원본 페이지 URL을 그대로 공유하는 행위',
    '사이트에서 다운로드 가능하다고 명시한 이력서와 포트폴리오 파일의 개인적 열람',
  ],
  restrictions: [
    '권리자의 허락 없이 사이트의 문구·디자인·이미지·영상 전부 또는 일부를 복제하거나 다른 매체에 재게시·재배포하는 행위',
    '원본 콘텐츠를 번역·편집·가공해 별도의 2차적저작물로 공개하는 행위',
    '콘텐츠를 데이터셋 구성, 자동 수집 또는 AI 모델 학습에 사용하는 행위',
    '판매·광고·유료 교육·기업 홍보 등 영리 목적으로 사용하는 행위',
  ],
  automatedAccess: [
    '사전 허가 없는 크롤링·스크래핑·미러링·대량 다운로드·검색 색인·웹 아카이빙을 허용하지 않습니다.',
    '포트폴리오 콘텐츠를 검색·추천·생성형 AI·기계학습용 데이터셋 또는 임베딩에 수집하거나 사용하는 행위를 허용하지 않습니다.',
    'robots.txt, robots meta, TDMRep와 llms.txt는 이러한 권리 유보 의사를 기계 판독 가능한 형태로 표시하며, 이를 우회해도 이용 허가가 부여되지 않습니다.',
  ],
  attribution: {
    required: '별도 사전 서면 허가를 받아 콘텐츠를 인용·재사용하는 경우에도 저작자, 포트폴리오명, 원본 URL을 결과물과 관련 작업물에 명확히 표시해야 합니다.',
    format: '출처: 윤정민 포트폴리오 — https://yjmini.github.io/portfolio-site/',
    warning: '출처 표시는 이용 허가를 의미하지 않으며, 출처를 남겼다는 이유만으로 복제·재배포·2차적저작물 작성이 허용되지 않습니다.',
  },
  separateLicenses: '프로젝트 저장소나 개별 파일에 별도 라이선스 또는 출처가 표시된 경우 해당 조건이 우선합니다. 팀 프로젝트 공동 산출물과 제3자 자료의 권리는 각 팀·원저작자·권리자에게 귀속됩니다.',
  contact: '발표, 기사, 교육 자료, 협업 제안 등 단순 열람을 넘어서는 이용이 필요하면 사용 목적과 범위를 적어 먼저 문의해 주세요.',
  english: 'Unless otherwise noted, original copy, editorial composition, graphics, photographs, and videos owned by Yoon Jeongmin are protected. Separate project licenses take precedence. Team-project materials and third-party content remain the property of their respective rights holders. Reproduction, modification, redistribution, automated crawling, dataset collection, AI training, and commercial use require prior written permission unless applicable law or a separate license allows them. Authorized reuse must credit Yoon Jeongmin, this portfolio, and the canonical URL; attribution alone does not grant permission.',
  projectNotices: [
    {
      project: 'THING',
      rightsHolder: 'C103 Team',
      license: 'Apache-2.0',
      source: 'https://github.com/SeMinKong/THING',
      licenseUrl: 'https://github.com/SeMinKong/THING/blob/main/LICENSE',
      noticeUrl: 'assets/projects/thing/NOTICE.txt',
      note: 'THING 공동 프로젝트 시연 미디어와 제작 이미지는 C103 Team 공동 산출물이며, 프로젝트 저장소의 Apache-2.0 표시와 출처를 함께 제공합니다.',
    },
    {
      project: '스마트 조립·무인 운송 시스템',
      rightsHolder: '윤정민 및 프로젝트 팀',
      license: '소스 코드: MIT · 미디어: 권리 유보',
      source: 'https://github.com/yjmini/smart-assembly-transport',
      licenseUrl: 'https://github.com/yjmini/smart-assembly-transport/blob/main/LICENSE',
      noticeUrl: 'assets/projects/smart-assembly/NOTICE.txt',
      note: '소스 코드는 MIT License로 공개되어 있습니다. 사진·화면 캡처·발표 자료는 팀 공동 산출물이며, 포트폴리오 표시 외 복제·수정·재배포 권한은 별도로 부여하지 않습니다.',
    },
  ],
  assetNotices: [
    {
      asset: '경기천년제목',
      rightsHolder: '경기도',
      license: '공공누리 제1유형 · 경기도 서체 이용 조건',
      source: 'https://www.gg.go.kr/contents/contents.do?ciIdx=679&menuId=2457',
      licenseUrl: 'https://www.kogl.or.kr/info/licenseType1.do',
      noticeUrl: 'assets/fonts/gyeonggi-title/NOTICE.txt',
      note: '경기도가 배포한 공식 WOFF를 자체 호스팅합니다. 웹·인쇄·영상·프로그램 탑재에 사용할 수 있으며, 폰트 자체의 판매 또는 유료 양도는 허용되지 않습니다.',
    },
  ],
}
